### PR TITLE
Airport Challenge submission - Bananas International Airport

### PR DESCRIPTION
**Pull request by anitacanita**

### CODE REVIEW

**Comment by tansaku** [comment]
Looking good @anitacanita !

I think you pretty much already know where any remaining changes are needed.  My top tips

* remove all commented code before submission
* use do ... end for { ... } to help with splitting over long lines
* move weather functionality into a module for SRP purposes

The issue you brought up about stubbing is important.  You've stubbed globally in the old style as we discussed - there is a new style and there is a way to stub locally that we can look at today.

Fix these few things up and it'll be checkered flag time :-)

:construction:

**Comment by tansaku** [comment]
p.s. there is some room for advanced tightening on some of your if statements (this it common for many) - will look at that today in byte - not required for flag, but good to know :-)

**Comment by anitacanita** [comment]
Thanks Sam!

I have deleted all comments and last night I put the random weather
generator into a module, I'm missing anything else? Maybe my `stormy?`
method should also be in that module?

I'm also unsure how to use do .. end in rspec, but I guess that after some
research I'll figure that one out.

This stubbing issue is driving me mad! I hope you can shed some light on
this issue :)

Ana


On 11 September 2015 at 07:36, Sam Joseph <notifications@github.com> wrote:

> p.s. there is some room for advanced tightening on some of your if
> statements (this it common for many) - will look at that today in byte -
> not required for flag, but good to know :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/airport_challenge/pull/166#issuecomment-139464865>
> .
>



-- 
Ana Carlos
07927 269 864

**Comment by tansaku** [comment]
so I think we are almost sticker - let me know when ready for final review :-)

**Comment by anitacanita** [comment]
I think I'm ready to go :D

On 11 September 2015 at 10:47, Sam Joseph <notifications@github.com> wrote:

> so I think we are almost sticker - let me know when ready for final review
> :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/airport_challenge/pull/166#issuecomment-139502294>
> .
>



-- 
Ana Carlos
07927 269 864

**Pull request closed without merging**
